name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Codecov
        uses: codecov/codecov-action@v2.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          
      # - name: Golint
      #   run: |
      #     curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.10.2
      #     go get -u golang.org/x/lint/golint
      #     golangci-lint run
      #     golint -set_exit_status
      # - name: Test
      #   run: go test ./... -v
